version: '3.3'
services: 
  cache:
    container_name: redis-golang
    image: redis
    command: redis-server
    networks:
      extnetwork-2:
        ipv4_address: 172.24.0.3
    ports:
      - 6379:6379

  function:
    container_name: function-service
    image: function-service:latest
    networks:
      extnetwork-2:
        ipv4_address: 172.24.0.4
    ports:
      - 50051:50051
  
  backend:
    container_name: backend
    image: backend:latest
    networks:
      extnetwork-2:
        ipv4_address: 172.24.0.5
    depends_on:
      - cahce
      - function
    ports:
      - 50052:50052
  

networks:
   extnetwork-2:
      ipam:
         config:
         - subnet: 172.24.0.0/16