# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import impactEffect_pb2 as impactEffect__pb2


class ImpactEffectServiceStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKineticEnergy = channel.unary_unary(
                '/impactEffect.ImpactEffectService/GetKineticEnergy',
                request_serializer=impactEffect__pb2.Impactor.SerializeToString,
                response_deserializer=impactEffect__pb2.KineticEnergy.FromString,
                )


class ImpactEffectServiceServicer(object):
    """Interface exported by the server.
    """

    def GetKineticEnergy(self, request, context):
        """A simple the function of ImpactEffect for test
        calculte the Kinetic_energy of the impactor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImpactEffectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKineticEnergy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKineticEnergy,
                    request_deserializer=impactEffect__pb2.Impactor.FromString,
                    response_serializer=impactEffect__pb2.KineticEnergy.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'impactEffect.ImpactEffectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImpactEffectService(object):
    """Interface exported by the server.
    """

    @staticmethod
    def GetKineticEnergy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/impactEffect.ImpactEffectService/GetKineticEnergy',
            impactEffect__pb2.Impactor.SerializeToString,
            impactEffect__pb2.KineticEnergy.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
