// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: impactEffect.proto

package impactEffect

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImpactEffectServiceClient is the client API for ImpactEffectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImpactEffectServiceClient interface {
	// A simple the function of ImpactEffect for test
	// calculte the Kinetic_energy of the impactor
	Cal_KineticEnergy(ctx context.Context, in *Cal_KineticEnergyRequest, opts ...grpc.CallOption) (*Cal_KineticEnergyResponse, error)
	// calculate the Kinetic_energy of the impactor
	CalKineticEnergyMegatons(ctx context.Context, in *CalKineticEnergyMegatonsRequest, opts ...grpc.CallOption) (*CalKineticEnergyMegatonsResponse, error)
	// calculate the rec time of the impactor
	CalRecTime(ctx context.Context, in *CalRecTimeRequest, opts ...grpc.CallOption) (*CalRecTimeResponse, error)
	// calculate the i_factor of the impactor
	CalIFactor(ctx context.Context, in *CalIFactorRequest, opts ...grpc.CallOption) (*CalIFactorResponse, error)
	BurstVelocityAtZero(ctx context.Context, in *BurstVelocityAtZeroRequest, opts ...grpc.CallOption) (*BurstVelocityAtZeroResponse, error)
	AltitudeOfBreakup(ctx context.Context, in *AltitudeOfBreakupRequest, opts ...grpc.CallOption) (*AltitudeOfBreakupResponse, error)
	VelocityAtBreakup(ctx context.Context, in *VelocityAtBreakupRequest, opts ...grpc.CallOption) (*VelocityAtBreakupResponse, error)
	DispersionLengthScale(ctx context.Context, in *DispersionLengthScaleRequest, opts ...grpc.CallOption) (*DispersionLengthScaleResponse, error)
	AirburstAltitude(ctx context.Context, in *AirburstAltitudeRequest, opts ...grpc.CallOption) (*AirburstAltitudeResponse, error)
	BrustVelocity(ctx context.Context, in *BrustVelocityRequest, opts ...grpc.CallOption) (*BrustVelocityResponse, error)
	DispersionOfImpactor(ctx context.Context, in *DispersionOfImpactorRequest, opts ...grpc.CallOption) (*DispersionOfImpactorResponse, error)
	FractionOfMomentum(ctx context.Context, in *FractionOfMomentumRequest, opts ...grpc.CallOption) (*FractionOfMomentumResponse, error)
	CalTrotChange(ctx context.Context, in *CalTrotChangeRequest, opts ...grpc.CallOption) (*CalTrotChangeResponse, error)
	CalEnergyAtmosphere(ctx context.Context, in *CalEnergyAtmosphereRequest, opts ...grpc.CallOption) (*CalEnergyAtmosphereResponse, error)
	CalEnergyBlastSurface(ctx context.Context, in *CalEnergyBlastSurfaceRequest, opts ...grpc.CallOption) (*CalEnergyBlastSurfaceResponse, error)
	CalMassOfWater(ctx context.Context, in *CalMassOfWaterRequest, opts ...grpc.CallOption) (*CalMassOfWaterResponse, error)
	CalVelocityProjectile(ctx context.Context, in *CalVelocityProjectileRequest, opts ...grpc.CallOption) (*CalVelocityProjectileResponse, error)
	CalEnergyAtSeafloor(ctx context.Context, in *CalEnergyAtSeafloorRequest, opts ...grpc.CallOption) (*CalEnergyAtSeafloorResponse, error)
	CalEPIcentralAngle(ctx context.Context, in *CalEPIcentralAngleRequest, opts ...grpc.CallOption) (*CalEPIcentralAngleResponse, error)
	CalScalingDiameterConstant(ctx context.Context, in *CalScalingDiameterConstantRequest, opts ...grpc.CallOption) (*CalScalingDiameterConstantResponse, error)
	CalAnglefac(ctx context.Context, in *CalAnglefacRequest, opts ...grpc.CallOption) (*CalAnglefacResponse, error)
	CalWdiameter(ctx context.Context, in *CalWdiameterRequest, opts ...grpc.CallOption) (*CalWdiameterResponse, error)
	CalTransientCraterDiameter(ctx context.Context, in *CalTransientCraterDiameterRequest, opts ...grpc.CallOption) (*CalTransientCraterDiameterResponse, error)
	CalDepthr(ctx context.Context, in *CalDepthrRequest, opts ...grpc.CallOption) (*CalDepthrResponse, error)
	CalCdiamater(ctx context.Context, in *CalCdiamaterRequest, opts ...grpc.CallOption) (*CalCdiamaterResponse, error)
	CalDepthfr(ctx context.Context, in *CalDepthfrRequest, opts ...grpc.CallOption) (*CalDepthfrResponse, error)
	CalVCrater(ctx context.Context, in *CalVCraterRequest, opts ...grpc.CallOption) (*CalVCraterResponse, error)
	CalVratio(ctx context.Context, in *CalVratioRequest, opts ...grpc.CallOption) (*CalVratioResponse, error)
	CalVCraterVRation(ctx context.Context, in *CalVCraterVRationRequest, opts ...grpc.CallOption) (*CalVCraterVRationResponse, error)
	CalVMelt(ctx context.Context, in *CalVMeltRequest, opts ...grpc.CallOption) (*CalVMeltResponse, error)
	CalMratioAndMcratio(ctx context.Context, in *CalMratioAndMcratioRequest, opts ...grpc.CallOption) (*CalMratioAndMcratioResponse, error)
	CalEjectArrival(ctx context.Context, in *CalEjectArrivalRequest, opts ...grpc.CallOption) (*CalEjectArrivalResponse, error)
	CalEjectaThickness(ctx context.Context, in *CalEjectaThicknessRequest, opts ...grpc.CallOption) (*CalEjectaThicknessResponse, error)
	CalDFrag(ctx context.Context, in *CalDFragRequest, opts ...grpc.CallOption) (*CalDFragResponse, error)
	CalThemal(ctx context.Context, in *CalThemalRequest, opts ...grpc.CallOption) (*CalThemalResponse, error)
	CalMagnitude(ctx context.Context, in *CalMagnitudeRequest, opts ...grpc.CallOption) (*CalMagnitudeResponse, error)
	CalMagnitude2(ctx context.Context, in *CalMagnitude2Request, opts ...grpc.CallOption) (*CalMagnitude2Response, error)
	CalShockArrival(ctx context.Context, in *CalShockArrivalRequest, opts ...grpc.CallOption) (*CalShockArrivalResponse, error)
	CalVmax(ctx context.Context, in *CalVmaxRequest, opts ...grpc.CallOption) (*CalVmaxResponse, error)
	CalShockDamage(ctx context.Context, in *CalShockDamageRequest, opts ...grpc.CallOption) (*CalShockDamageResponse, error)
	CalDecLevel(ctx context.Context, in *CalDecLevelRequest, opts ...grpc.CallOption) (*CalDecLevelResponse, error)
	Cal_TsunamiArrivalTime(ctx context.Context, in *Cal_TsunamiArrivalTimeRequest, opts ...grpc.CallOption) (*Cal_TsunamiArrivalTimeResponse, error)
	Cal_WaveAmplitudeUpperLimit(ctx context.Context, in *Cal_WaveAmplitudeUpperLimitRequest, opts ...grpc.CallOption) (*Cal_WaveAmplitudeUpperLimitResponse, error)
	Cal_WaveAmplitudeLowerLimit(ctx context.Context, in *Cal_WaveAmplitudeLowerLimitRequest, opts ...grpc.CallOption) (*Cal_WaveAmplitudeLowerLimitResponse, error)
}

type impactEffectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImpactEffectServiceClient(cc grpc.ClientConnInterface) ImpactEffectServiceClient {
	return &impactEffectServiceClient{cc}
}

func (c *impactEffectServiceClient) Cal_KineticEnergy(ctx context.Context, in *Cal_KineticEnergyRequest, opts ...grpc.CallOption) (*Cal_KineticEnergyResponse, error) {
	out := new(Cal_KineticEnergyResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_Kinetic_energy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalKineticEnergyMegatons(ctx context.Context, in *CalKineticEnergyMegatonsRequest, opts ...grpc.CallOption) (*CalKineticEnergyMegatonsResponse, error) {
	out := new(CalKineticEnergyMegatonsResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_kinetic_energy_megatons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalRecTime(ctx context.Context, in *CalRecTimeRequest, opts ...grpc.CallOption) (*CalRecTimeResponse, error) {
	out := new(CalRecTimeResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_rec_time", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalIFactor(ctx context.Context, in *CalIFactorRequest, opts ...grpc.CallOption) (*CalIFactorResponse, error) {
	out := new(CalIFactorResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_i_factor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) BurstVelocityAtZero(ctx context.Context, in *BurstVelocityAtZeroRequest, opts ...grpc.CallOption) (*BurstVelocityAtZeroResponse, error) {
	out := new(BurstVelocityAtZeroResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/burst_velocity_at_zero", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) AltitudeOfBreakup(ctx context.Context, in *AltitudeOfBreakupRequest, opts ...grpc.CallOption) (*AltitudeOfBreakupResponse, error) {
	out := new(AltitudeOfBreakupResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/altitude_of_breakup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) VelocityAtBreakup(ctx context.Context, in *VelocityAtBreakupRequest, opts ...grpc.CallOption) (*VelocityAtBreakupResponse, error) {
	out := new(VelocityAtBreakupResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/velocity_at_breakup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) DispersionLengthScale(ctx context.Context, in *DispersionLengthScaleRequest, opts ...grpc.CallOption) (*DispersionLengthScaleResponse, error) {
	out := new(DispersionLengthScaleResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/dispersion_length_scale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) AirburstAltitude(ctx context.Context, in *AirburstAltitudeRequest, opts ...grpc.CallOption) (*AirburstAltitudeResponse, error) {
	out := new(AirburstAltitudeResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/airburst_altitude", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) BrustVelocity(ctx context.Context, in *BrustVelocityRequest, opts ...grpc.CallOption) (*BrustVelocityResponse, error) {
	out := new(BrustVelocityResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/brust_velocity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) DispersionOfImpactor(ctx context.Context, in *DispersionOfImpactorRequest, opts ...grpc.CallOption) (*DispersionOfImpactorResponse, error) {
	out := new(DispersionOfImpactorResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/dispersion_of_impactor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) FractionOfMomentum(ctx context.Context, in *FractionOfMomentumRequest, opts ...grpc.CallOption) (*FractionOfMomentumResponse, error) {
	out := new(FractionOfMomentumResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/fraction_of_momentum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalTrotChange(ctx context.Context, in *CalTrotChangeRequest, opts ...grpc.CallOption) (*CalTrotChangeResponse, error) {
	out := new(CalTrotChangeResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_trot_change", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalEnergyAtmosphere(ctx context.Context, in *CalEnergyAtmosphereRequest, opts ...grpc.CallOption) (*CalEnergyAtmosphereResponse, error) {
	out := new(CalEnergyAtmosphereResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_energy_atmosphere", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalEnergyBlastSurface(ctx context.Context, in *CalEnergyBlastSurfaceRequest, opts ...grpc.CallOption) (*CalEnergyBlastSurfaceResponse, error) {
	out := new(CalEnergyBlastSurfaceResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_energy_blast_surface", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalMassOfWater(ctx context.Context, in *CalMassOfWaterRequest, opts ...grpc.CallOption) (*CalMassOfWaterResponse, error) {
	out := new(CalMassOfWaterResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_mass_of_water", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalVelocityProjectile(ctx context.Context, in *CalVelocityProjectileRequest, opts ...grpc.CallOption) (*CalVelocityProjectileResponse, error) {
	out := new(CalVelocityProjectileResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_velocity_projectile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalEnergyAtSeafloor(ctx context.Context, in *CalEnergyAtSeafloorRequest, opts ...grpc.CallOption) (*CalEnergyAtSeafloorResponse, error) {
	out := new(CalEnergyAtSeafloorResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_energy_at_seafloor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalEPIcentralAngle(ctx context.Context, in *CalEPIcentralAngleRequest, opts ...grpc.CallOption) (*CalEPIcentralAngleResponse, error) {
	out := new(CalEPIcentralAngleResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_ePIcentral_angle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalScalingDiameterConstant(ctx context.Context, in *CalScalingDiameterConstantRequest, opts ...grpc.CallOption) (*CalScalingDiameterConstantResponse, error) {
	out := new(CalScalingDiameterConstantResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_scaling_diameter_constant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalAnglefac(ctx context.Context, in *CalAnglefacRequest, opts ...grpc.CallOption) (*CalAnglefacResponse, error) {
	out := new(CalAnglefacResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_anglefac", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalWdiameter(ctx context.Context, in *CalWdiameterRequest, opts ...grpc.CallOption) (*CalWdiameterResponse, error) {
	out := new(CalWdiameterResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_wdiameter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalTransientCraterDiameter(ctx context.Context, in *CalTransientCraterDiameterRequest, opts ...grpc.CallOption) (*CalTransientCraterDiameterResponse, error) {
	out := new(CalTransientCraterDiameterResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_transient_crater_diameter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalDepthr(ctx context.Context, in *CalDepthrRequest, opts ...grpc.CallOption) (*CalDepthrResponse, error) {
	out := new(CalDepthrResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_depthr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalCdiamater(ctx context.Context, in *CalCdiamaterRequest, opts ...grpc.CallOption) (*CalCdiamaterResponse, error) {
	out := new(CalCdiamaterResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_cdiamater", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalDepthfr(ctx context.Context, in *CalDepthfrRequest, opts ...grpc.CallOption) (*CalDepthfrResponse, error) {
	out := new(CalDepthfrResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_depthfr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalVCrater(ctx context.Context, in *CalVCraterRequest, opts ...grpc.CallOption) (*CalVCraterResponse, error) {
	out := new(CalVCraterResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_vCrater", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalVratio(ctx context.Context, in *CalVratioRequest, opts ...grpc.CallOption) (*CalVratioResponse, error) {
	out := new(CalVratioResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_vratio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalVCraterVRation(ctx context.Context, in *CalVCraterVRationRequest, opts ...grpc.CallOption) (*CalVCraterVRationResponse, error) {
	out := new(CalVCraterVRationResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_vCrater_vRation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalVMelt(ctx context.Context, in *CalVMeltRequest, opts ...grpc.CallOption) (*CalVMeltResponse, error) {
	out := new(CalVMeltResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_vMelt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalMratioAndMcratio(ctx context.Context, in *CalMratioAndMcratioRequest, opts ...grpc.CallOption) (*CalMratioAndMcratioResponse, error) {
	out := new(CalMratioAndMcratioResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_mratio_and_mcratio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalEjectArrival(ctx context.Context, in *CalEjectArrivalRequest, opts ...grpc.CallOption) (*CalEjectArrivalResponse, error) {
	out := new(CalEjectArrivalResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_eject_arrival", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalEjectaThickness(ctx context.Context, in *CalEjectaThicknessRequest, opts ...grpc.CallOption) (*CalEjectaThicknessResponse, error) {
	out := new(CalEjectaThicknessResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_ejecta_thickness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalDFrag(ctx context.Context, in *CalDFragRequest, opts ...grpc.CallOption) (*CalDFragResponse, error) {
	out := new(CalDFragResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_d_frag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalThemal(ctx context.Context, in *CalThemalRequest, opts ...grpc.CallOption) (*CalThemalResponse, error) {
	out := new(CalThemalResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_themal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalMagnitude(ctx context.Context, in *CalMagnitudeRequest, opts ...grpc.CallOption) (*CalMagnitudeResponse, error) {
	out := new(CalMagnitudeResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_magnitude", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalMagnitude2(ctx context.Context, in *CalMagnitude2Request, opts ...grpc.CallOption) (*CalMagnitude2Response, error) {
	out := new(CalMagnitude2Response)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_magnitude2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalShockArrival(ctx context.Context, in *CalShockArrivalRequest, opts ...grpc.CallOption) (*CalShockArrivalResponse, error) {
	out := new(CalShockArrivalResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_shock_arrival", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalVmax(ctx context.Context, in *CalVmaxRequest, opts ...grpc.CallOption) (*CalVmaxResponse, error) {
	out := new(CalVmaxResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_vmax", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalShockDamage(ctx context.Context, in *CalShockDamageRequest, opts ...grpc.CallOption) (*CalShockDamageResponse, error) {
	out := new(CalShockDamageResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_shock_damage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) CalDecLevel(ctx context.Context, in *CalDecLevelRequest, opts ...grpc.CallOption) (*CalDecLevelResponse, error) {
	out := new(CalDecLevelResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_dec_level", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) Cal_TsunamiArrivalTime(ctx context.Context, in *Cal_TsunamiArrivalTimeRequest, opts ...grpc.CallOption) (*Cal_TsunamiArrivalTimeResponse, error) {
	out := new(Cal_TsunamiArrivalTimeResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_TsunamiArrivalTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) Cal_WaveAmplitudeUpperLimit(ctx context.Context, in *Cal_WaveAmplitudeUpperLimitRequest, opts ...grpc.CallOption) (*Cal_WaveAmplitudeUpperLimitResponse, error) {
	out := new(Cal_WaveAmplitudeUpperLimitResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_WaveAmplitudeUpperLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impactEffectServiceClient) Cal_WaveAmplitudeLowerLimit(ctx context.Context, in *Cal_WaveAmplitudeLowerLimitRequest, opts ...grpc.CallOption) (*Cal_WaveAmplitudeLowerLimitResponse, error) {
	out := new(Cal_WaveAmplitudeLowerLimitResponse)
	err := c.cc.Invoke(ctx, "/impactEffect.ImpactEffectService/cal_WaveAmplitudeLowerLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImpactEffectServiceServer is the server API for ImpactEffectService service.
// All implementations must embed UnimplementedImpactEffectServiceServer
// for forward compatibility
type ImpactEffectServiceServer interface {
	// A simple the function of ImpactEffect for test
	// calculte the Kinetic_energy of the impactor
	Cal_KineticEnergy(context.Context, *Cal_KineticEnergyRequest) (*Cal_KineticEnergyResponse, error)
	// calculate the Kinetic_energy of the impactor
	CalKineticEnergyMegatons(context.Context, *CalKineticEnergyMegatonsRequest) (*CalKineticEnergyMegatonsResponse, error)
	// calculate the rec time of the impactor
	CalRecTime(context.Context, *CalRecTimeRequest) (*CalRecTimeResponse, error)
	// calculate the i_factor of the impactor
	CalIFactor(context.Context, *CalIFactorRequest) (*CalIFactorResponse, error)
	BurstVelocityAtZero(context.Context, *BurstVelocityAtZeroRequest) (*BurstVelocityAtZeroResponse, error)
	AltitudeOfBreakup(context.Context, *AltitudeOfBreakupRequest) (*AltitudeOfBreakupResponse, error)
	VelocityAtBreakup(context.Context, *VelocityAtBreakupRequest) (*VelocityAtBreakupResponse, error)
	DispersionLengthScale(context.Context, *DispersionLengthScaleRequest) (*DispersionLengthScaleResponse, error)
	AirburstAltitude(context.Context, *AirburstAltitudeRequest) (*AirburstAltitudeResponse, error)
	BrustVelocity(context.Context, *BrustVelocityRequest) (*BrustVelocityResponse, error)
	DispersionOfImpactor(context.Context, *DispersionOfImpactorRequest) (*DispersionOfImpactorResponse, error)
	FractionOfMomentum(context.Context, *FractionOfMomentumRequest) (*FractionOfMomentumResponse, error)
	CalTrotChange(context.Context, *CalTrotChangeRequest) (*CalTrotChangeResponse, error)
	CalEnergyAtmosphere(context.Context, *CalEnergyAtmosphereRequest) (*CalEnergyAtmosphereResponse, error)
	CalEnergyBlastSurface(context.Context, *CalEnergyBlastSurfaceRequest) (*CalEnergyBlastSurfaceResponse, error)
	CalMassOfWater(context.Context, *CalMassOfWaterRequest) (*CalMassOfWaterResponse, error)
	CalVelocityProjectile(context.Context, *CalVelocityProjectileRequest) (*CalVelocityProjectileResponse, error)
	CalEnergyAtSeafloor(context.Context, *CalEnergyAtSeafloorRequest) (*CalEnergyAtSeafloorResponse, error)
	CalEPIcentralAngle(context.Context, *CalEPIcentralAngleRequest) (*CalEPIcentralAngleResponse, error)
	CalScalingDiameterConstant(context.Context, *CalScalingDiameterConstantRequest) (*CalScalingDiameterConstantResponse, error)
	CalAnglefac(context.Context, *CalAnglefacRequest) (*CalAnglefacResponse, error)
	CalWdiameter(context.Context, *CalWdiameterRequest) (*CalWdiameterResponse, error)
	CalTransientCraterDiameter(context.Context, *CalTransientCraterDiameterRequest) (*CalTransientCraterDiameterResponse, error)
	CalDepthr(context.Context, *CalDepthrRequest) (*CalDepthrResponse, error)
	CalCdiamater(context.Context, *CalCdiamaterRequest) (*CalCdiamaterResponse, error)
	CalDepthfr(context.Context, *CalDepthfrRequest) (*CalDepthfrResponse, error)
	CalVCrater(context.Context, *CalVCraterRequest) (*CalVCraterResponse, error)
	CalVratio(context.Context, *CalVratioRequest) (*CalVratioResponse, error)
	CalVCraterVRation(context.Context, *CalVCraterVRationRequest) (*CalVCraterVRationResponse, error)
	CalVMelt(context.Context, *CalVMeltRequest) (*CalVMeltResponse, error)
	CalMratioAndMcratio(context.Context, *CalMratioAndMcratioRequest) (*CalMratioAndMcratioResponse, error)
	CalEjectArrival(context.Context, *CalEjectArrivalRequest) (*CalEjectArrivalResponse, error)
	CalEjectaThickness(context.Context, *CalEjectaThicknessRequest) (*CalEjectaThicknessResponse, error)
	CalDFrag(context.Context, *CalDFragRequest) (*CalDFragResponse, error)
	CalThemal(context.Context, *CalThemalRequest) (*CalThemalResponse, error)
	CalMagnitude(context.Context, *CalMagnitudeRequest) (*CalMagnitudeResponse, error)
	CalMagnitude2(context.Context, *CalMagnitude2Request) (*CalMagnitude2Response, error)
	CalShockArrival(context.Context, *CalShockArrivalRequest) (*CalShockArrivalResponse, error)
	CalVmax(context.Context, *CalVmaxRequest) (*CalVmaxResponse, error)
	CalShockDamage(context.Context, *CalShockDamageRequest) (*CalShockDamageResponse, error)
	CalDecLevel(context.Context, *CalDecLevelRequest) (*CalDecLevelResponse, error)
	Cal_TsunamiArrivalTime(context.Context, *Cal_TsunamiArrivalTimeRequest) (*Cal_TsunamiArrivalTimeResponse, error)
	Cal_WaveAmplitudeUpperLimit(context.Context, *Cal_WaveAmplitudeUpperLimitRequest) (*Cal_WaveAmplitudeUpperLimitResponse, error)
	Cal_WaveAmplitudeLowerLimit(context.Context, *Cal_WaveAmplitudeLowerLimitRequest) (*Cal_WaveAmplitudeLowerLimitResponse, error)
	mustEmbedUnimplementedImpactEffectServiceServer()
}

// UnimplementedImpactEffectServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImpactEffectServiceServer struct {
}

func (UnimplementedImpactEffectServiceServer) Cal_KineticEnergy(context.Context, *Cal_KineticEnergyRequest) (*Cal_KineticEnergyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cal_KineticEnergy not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalKineticEnergyMegatons(context.Context, *CalKineticEnergyMegatonsRequest) (*CalKineticEnergyMegatonsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalKineticEnergyMegatons not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalRecTime(context.Context, *CalRecTimeRequest) (*CalRecTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalRecTime not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalIFactor(context.Context, *CalIFactorRequest) (*CalIFactorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalIFactor not implemented")
}
func (UnimplementedImpactEffectServiceServer) BurstVelocityAtZero(context.Context, *BurstVelocityAtZeroRequest) (*BurstVelocityAtZeroResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BurstVelocityAtZero not implemented")
}
func (UnimplementedImpactEffectServiceServer) AltitudeOfBreakup(context.Context, *AltitudeOfBreakupRequest) (*AltitudeOfBreakupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AltitudeOfBreakup not implemented")
}
func (UnimplementedImpactEffectServiceServer) VelocityAtBreakup(context.Context, *VelocityAtBreakupRequest) (*VelocityAtBreakupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VelocityAtBreakup not implemented")
}
func (UnimplementedImpactEffectServiceServer) DispersionLengthScale(context.Context, *DispersionLengthScaleRequest) (*DispersionLengthScaleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DispersionLengthScale not implemented")
}
func (UnimplementedImpactEffectServiceServer) AirburstAltitude(context.Context, *AirburstAltitudeRequest) (*AirburstAltitudeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AirburstAltitude not implemented")
}
func (UnimplementedImpactEffectServiceServer) BrustVelocity(context.Context, *BrustVelocityRequest) (*BrustVelocityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BrustVelocity not implemented")
}
func (UnimplementedImpactEffectServiceServer) DispersionOfImpactor(context.Context, *DispersionOfImpactorRequest) (*DispersionOfImpactorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DispersionOfImpactor not implemented")
}
func (UnimplementedImpactEffectServiceServer) FractionOfMomentum(context.Context, *FractionOfMomentumRequest) (*FractionOfMomentumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FractionOfMomentum not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalTrotChange(context.Context, *CalTrotChangeRequest) (*CalTrotChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalTrotChange not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalEnergyAtmosphere(context.Context, *CalEnergyAtmosphereRequest) (*CalEnergyAtmosphereResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalEnergyAtmosphere not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalEnergyBlastSurface(context.Context, *CalEnergyBlastSurfaceRequest) (*CalEnergyBlastSurfaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalEnergyBlastSurface not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalMassOfWater(context.Context, *CalMassOfWaterRequest) (*CalMassOfWaterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalMassOfWater not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalVelocityProjectile(context.Context, *CalVelocityProjectileRequest) (*CalVelocityProjectileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalVelocityProjectile not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalEnergyAtSeafloor(context.Context, *CalEnergyAtSeafloorRequest) (*CalEnergyAtSeafloorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalEnergyAtSeafloor not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalEPIcentralAngle(context.Context, *CalEPIcentralAngleRequest) (*CalEPIcentralAngleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalEPIcentralAngle not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalScalingDiameterConstant(context.Context, *CalScalingDiameterConstantRequest) (*CalScalingDiameterConstantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalScalingDiameterConstant not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalAnglefac(context.Context, *CalAnglefacRequest) (*CalAnglefacResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalAnglefac not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalWdiameter(context.Context, *CalWdiameterRequest) (*CalWdiameterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalWdiameter not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalTransientCraterDiameter(context.Context, *CalTransientCraterDiameterRequest) (*CalTransientCraterDiameterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalTransientCraterDiameter not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalDepthr(context.Context, *CalDepthrRequest) (*CalDepthrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalDepthr not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalCdiamater(context.Context, *CalCdiamaterRequest) (*CalCdiamaterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalCdiamater not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalDepthfr(context.Context, *CalDepthfrRequest) (*CalDepthfrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalDepthfr not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalVCrater(context.Context, *CalVCraterRequest) (*CalVCraterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalVCrater not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalVratio(context.Context, *CalVratioRequest) (*CalVratioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalVratio not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalVCraterVRation(context.Context, *CalVCraterVRationRequest) (*CalVCraterVRationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalVCraterVRation not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalVMelt(context.Context, *CalVMeltRequest) (*CalVMeltResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalVMelt not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalMratioAndMcratio(context.Context, *CalMratioAndMcratioRequest) (*CalMratioAndMcratioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalMratioAndMcratio not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalEjectArrival(context.Context, *CalEjectArrivalRequest) (*CalEjectArrivalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalEjectArrival not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalEjectaThickness(context.Context, *CalEjectaThicknessRequest) (*CalEjectaThicknessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalEjectaThickness not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalDFrag(context.Context, *CalDFragRequest) (*CalDFragResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalDFrag not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalThemal(context.Context, *CalThemalRequest) (*CalThemalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalThemal not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalMagnitude(context.Context, *CalMagnitudeRequest) (*CalMagnitudeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalMagnitude not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalMagnitude2(context.Context, *CalMagnitude2Request) (*CalMagnitude2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalMagnitude2 not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalShockArrival(context.Context, *CalShockArrivalRequest) (*CalShockArrivalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalShockArrival not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalVmax(context.Context, *CalVmaxRequest) (*CalVmaxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalVmax not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalShockDamage(context.Context, *CalShockDamageRequest) (*CalShockDamageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalShockDamage not implemented")
}
func (UnimplementedImpactEffectServiceServer) CalDecLevel(context.Context, *CalDecLevelRequest) (*CalDecLevelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalDecLevel not implemented")
}
func (UnimplementedImpactEffectServiceServer) Cal_TsunamiArrivalTime(context.Context, *Cal_TsunamiArrivalTimeRequest) (*Cal_TsunamiArrivalTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cal_TsunamiArrivalTime not implemented")
}
func (UnimplementedImpactEffectServiceServer) Cal_WaveAmplitudeUpperLimit(context.Context, *Cal_WaveAmplitudeUpperLimitRequest) (*Cal_WaveAmplitudeUpperLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cal_WaveAmplitudeUpperLimit not implemented")
}
func (UnimplementedImpactEffectServiceServer) Cal_WaveAmplitudeLowerLimit(context.Context, *Cal_WaveAmplitudeLowerLimitRequest) (*Cal_WaveAmplitudeLowerLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cal_WaveAmplitudeLowerLimit not implemented")
}
func (UnimplementedImpactEffectServiceServer) mustEmbedUnimplementedImpactEffectServiceServer() {}

// UnsafeImpactEffectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImpactEffectServiceServer will
// result in compilation errors.
type UnsafeImpactEffectServiceServer interface {
	mustEmbedUnimplementedImpactEffectServiceServer()
}

func RegisterImpactEffectServiceServer(s grpc.ServiceRegistrar, srv ImpactEffectServiceServer) {
	s.RegisterService(&ImpactEffectService_ServiceDesc, srv)
}

func _ImpactEffectService_Cal_KineticEnergy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cal_KineticEnergyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).Cal_KineticEnergy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_Kinetic_energy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).Cal_KineticEnergy(ctx, req.(*Cal_KineticEnergyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalKineticEnergyMegatons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalKineticEnergyMegatonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalKineticEnergyMegatons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_kinetic_energy_megatons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalKineticEnergyMegatons(ctx, req.(*CalKineticEnergyMegatonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalRecTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalRecTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalRecTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_rec_time",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalRecTime(ctx, req.(*CalRecTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalIFactor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalIFactorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalIFactor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_i_factor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalIFactor(ctx, req.(*CalIFactorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_BurstVelocityAtZero_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BurstVelocityAtZeroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).BurstVelocityAtZero(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/burst_velocity_at_zero",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).BurstVelocityAtZero(ctx, req.(*BurstVelocityAtZeroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_AltitudeOfBreakup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AltitudeOfBreakupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).AltitudeOfBreakup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/altitude_of_breakup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).AltitudeOfBreakup(ctx, req.(*AltitudeOfBreakupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_VelocityAtBreakup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VelocityAtBreakupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).VelocityAtBreakup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/velocity_at_breakup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).VelocityAtBreakup(ctx, req.(*VelocityAtBreakupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_DispersionLengthScale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispersionLengthScaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).DispersionLengthScale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/dispersion_length_scale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).DispersionLengthScale(ctx, req.(*DispersionLengthScaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_AirburstAltitude_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AirburstAltitudeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).AirburstAltitude(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/airburst_altitude",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).AirburstAltitude(ctx, req.(*AirburstAltitudeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_BrustVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrustVelocityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).BrustVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/brust_velocity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).BrustVelocity(ctx, req.(*BrustVelocityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_DispersionOfImpactor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispersionOfImpactorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).DispersionOfImpactor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/dispersion_of_impactor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).DispersionOfImpactor(ctx, req.(*DispersionOfImpactorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_FractionOfMomentum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FractionOfMomentumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).FractionOfMomentum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/fraction_of_momentum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).FractionOfMomentum(ctx, req.(*FractionOfMomentumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalTrotChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalTrotChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalTrotChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_trot_change",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalTrotChange(ctx, req.(*CalTrotChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalEnergyAtmosphere_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalEnergyAtmosphereRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalEnergyAtmosphere(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_energy_atmosphere",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalEnergyAtmosphere(ctx, req.(*CalEnergyAtmosphereRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalEnergyBlastSurface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalEnergyBlastSurfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalEnergyBlastSurface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_energy_blast_surface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalEnergyBlastSurface(ctx, req.(*CalEnergyBlastSurfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalMassOfWater_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalMassOfWaterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalMassOfWater(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_mass_of_water",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalMassOfWater(ctx, req.(*CalMassOfWaterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalVelocityProjectile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalVelocityProjectileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalVelocityProjectile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_velocity_projectile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalVelocityProjectile(ctx, req.(*CalVelocityProjectileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalEnergyAtSeafloor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalEnergyAtSeafloorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalEnergyAtSeafloor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_energy_at_seafloor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalEnergyAtSeafloor(ctx, req.(*CalEnergyAtSeafloorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalEPIcentralAngle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalEPIcentralAngleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalEPIcentralAngle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_ePIcentral_angle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalEPIcentralAngle(ctx, req.(*CalEPIcentralAngleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalScalingDiameterConstant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalScalingDiameterConstantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalScalingDiameterConstant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_scaling_diameter_constant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalScalingDiameterConstant(ctx, req.(*CalScalingDiameterConstantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalAnglefac_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalAnglefacRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalAnglefac(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_anglefac",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalAnglefac(ctx, req.(*CalAnglefacRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalWdiameter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalWdiameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalWdiameter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_wdiameter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalWdiameter(ctx, req.(*CalWdiameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalTransientCraterDiameter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalTransientCraterDiameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalTransientCraterDiameter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_transient_crater_diameter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalTransientCraterDiameter(ctx, req.(*CalTransientCraterDiameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalDepthr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalDepthrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalDepthr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_depthr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalDepthr(ctx, req.(*CalDepthrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalCdiamater_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalCdiamaterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalCdiamater(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_cdiamater",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalCdiamater(ctx, req.(*CalCdiamaterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalDepthfr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalDepthfrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalDepthfr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_depthfr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalDepthfr(ctx, req.(*CalDepthfrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalVCrater_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalVCraterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalVCrater(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_vCrater",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalVCrater(ctx, req.(*CalVCraterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalVratio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalVratioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalVratio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_vratio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalVratio(ctx, req.(*CalVratioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalVCraterVRation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalVCraterVRationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalVCraterVRation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_vCrater_vRation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalVCraterVRation(ctx, req.(*CalVCraterVRationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalVMelt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalVMeltRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalVMelt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_vMelt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalVMelt(ctx, req.(*CalVMeltRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalMratioAndMcratio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalMratioAndMcratioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalMratioAndMcratio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_mratio_and_mcratio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalMratioAndMcratio(ctx, req.(*CalMratioAndMcratioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalEjectArrival_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalEjectArrivalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalEjectArrival(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_eject_arrival",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalEjectArrival(ctx, req.(*CalEjectArrivalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalEjectaThickness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalEjectaThicknessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalEjectaThickness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_ejecta_thickness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalEjectaThickness(ctx, req.(*CalEjectaThicknessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalDFrag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalDFragRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalDFrag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_d_frag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalDFrag(ctx, req.(*CalDFragRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalThemal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalThemalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalThemal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_themal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalThemal(ctx, req.(*CalThemalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalMagnitude_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalMagnitudeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalMagnitude(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_magnitude",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalMagnitude(ctx, req.(*CalMagnitudeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalMagnitude2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalMagnitude2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalMagnitude2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_magnitude2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalMagnitude2(ctx, req.(*CalMagnitude2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalShockArrival_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalShockArrivalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalShockArrival(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_shock_arrival",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalShockArrival(ctx, req.(*CalShockArrivalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalVmax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalVmaxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalVmax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_vmax",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalVmax(ctx, req.(*CalVmaxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalShockDamage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalShockDamageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalShockDamage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_shock_damage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalShockDamage(ctx, req.(*CalShockDamageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_CalDecLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalDecLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).CalDecLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_dec_level",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).CalDecLevel(ctx, req.(*CalDecLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_Cal_TsunamiArrivalTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cal_TsunamiArrivalTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).Cal_TsunamiArrivalTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_TsunamiArrivalTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).Cal_TsunamiArrivalTime(ctx, req.(*Cal_TsunamiArrivalTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_Cal_WaveAmplitudeUpperLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cal_WaveAmplitudeUpperLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).Cal_WaveAmplitudeUpperLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_WaveAmplitudeUpperLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).Cal_WaveAmplitudeUpperLimit(ctx, req.(*Cal_WaveAmplitudeUpperLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImpactEffectService_Cal_WaveAmplitudeLowerLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cal_WaveAmplitudeLowerLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpactEffectServiceServer).Cal_WaveAmplitudeLowerLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impactEffect.ImpactEffectService/cal_WaveAmplitudeLowerLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpactEffectServiceServer).Cal_WaveAmplitudeLowerLimit(ctx, req.(*Cal_WaveAmplitudeLowerLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImpactEffectService_ServiceDesc is the grpc.ServiceDesc for ImpactEffectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImpactEffectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "impactEffect.ImpactEffectService",
	HandlerType: (*ImpactEffectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "cal_Kinetic_energy",
			Handler:    _ImpactEffectService_Cal_KineticEnergy_Handler,
		},
		{
			MethodName: "cal_kinetic_energy_megatons",
			Handler:    _ImpactEffectService_CalKineticEnergyMegatons_Handler,
		},
		{
			MethodName: "cal_rec_time",
			Handler:    _ImpactEffectService_CalRecTime_Handler,
		},
		{
			MethodName: "cal_i_factor",
			Handler:    _ImpactEffectService_CalIFactor_Handler,
		},
		{
			MethodName: "burst_velocity_at_zero",
			Handler:    _ImpactEffectService_BurstVelocityAtZero_Handler,
		},
		{
			MethodName: "altitude_of_breakup",
			Handler:    _ImpactEffectService_AltitudeOfBreakup_Handler,
		},
		{
			MethodName: "velocity_at_breakup",
			Handler:    _ImpactEffectService_VelocityAtBreakup_Handler,
		},
		{
			MethodName: "dispersion_length_scale",
			Handler:    _ImpactEffectService_DispersionLengthScale_Handler,
		},
		{
			MethodName: "airburst_altitude",
			Handler:    _ImpactEffectService_AirburstAltitude_Handler,
		},
		{
			MethodName: "brust_velocity",
			Handler:    _ImpactEffectService_BrustVelocity_Handler,
		},
		{
			MethodName: "dispersion_of_impactor",
			Handler:    _ImpactEffectService_DispersionOfImpactor_Handler,
		},
		{
			MethodName: "fraction_of_momentum",
			Handler:    _ImpactEffectService_FractionOfMomentum_Handler,
		},
		{
			MethodName: "cal_trot_change",
			Handler:    _ImpactEffectService_CalTrotChange_Handler,
		},
		{
			MethodName: "cal_energy_atmosphere",
			Handler:    _ImpactEffectService_CalEnergyAtmosphere_Handler,
		},
		{
			MethodName: "cal_energy_blast_surface",
			Handler:    _ImpactEffectService_CalEnergyBlastSurface_Handler,
		},
		{
			MethodName: "cal_mass_of_water",
			Handler:    _ImpactEffectService_CalMassOfWater_Handler,
		},
		{
			MethodName: "cal_velocity_projectile",
			Handler:    _ImpactEffectService_CalVelocityProjectile_Handler,
		},
		{
			MethodName: "cal_energy_at_seafloor",
			Handler:    _ImpactEffectService_CalEnergyAtSeafloor_Handler,
		},
		{
			MethodName: "cal_ePIcentral_angle",
			Handler:    _ImpactEffectService_CalEPIcentralAngle_Handler,
		},
		{
			MethodName: "cal_scaling_diameter_constant",
			Handler:    _ImpactEffectService_CalScalingDiameterConstant_Handler,
		},
		{
			MethodName: "cal_anglefac",
			Handler:    _ImpactEffectService_CalAnglefac_Handler,
		},
		{
			MethodName: "cal_wdiameter",
			Handler:    _ImpactEffectService_CalWdiameter_Handler,
		},
		{
			MethodName: "cal_transient_crater_diameter",
			Handler:    _ImpactEffectService_CalTransientCraterDiameter_Handler,
		},
		{
			MethodName: "cal_depthr",
			Handler:    _ImpactEffectService_CalDepthr_Handler,
		},
		{
			MethodName: "cal_cdiamater",
			Handler:    _ImpactEffectService_CalCdiamater_Handler,
		},
		{
			MethodName: "cal_depthfr",
			Handler:    _ImpactEffectService_CalDepthfr_Handler,
		},
		{
			MethodName: "cal_vCrater",
			Handler:    _ImpactEffectService_CalVCrater_Handler,
		},
		{
			MethodName: "cal_vratio",
			Handler:    _ImpactEffectService_CalVratio_Handler,
		},
		{
			MethodName: "cal_vCrater_vRation",
			Handler:    _ImpactEffectService_CalVCraterVRation_Handler,
		},
		{
			MethodName: "cal_vMelt",
			Handler:    _ImpactEffectService_CalVMelt_Handler,
		},
		{
			MethodName: "cal_mratio_and_mcratio",
			Handler:    _ImpactEffectService_CalMratioAndMcratio_Handler,
		},
		{
			MethodName: "cal_eject_arrival",
			Handler:    _ImpactEffectService_CalEjectArrival_Handler,
		},
		{
			MethodName: "cal_ejecta_thickness",
			Handler:    _ImpactEffectService_CalEjectaThickness_Handler,
		},
		{
			MethodName: "cal_d_frag",
			Handler:    _ImpactEffectService_CalDFrag_Handler,
		},
		{
			MethodName: "cal_themal",
			Handler:    _ImpactEffectService_CalThemal_Handler,
		},
		{
			MethodName: "cal_magnitude",
			Handler:    _ImpactEffectService_CalMagnitude_Handler,
		},
		{
			MethodName: "cal_magnitude2",
			Handler:    _ImpactEffectService_CalMagnitude2_Handler,
		},
		{
			MethodName: "cal_shock_arrival",
			Handler:    _ImpactEffectService_CalShockArrival_Handler,
		},
		{
			MethodName: "cal_vmax",
			Handler:    _ImpactEffectService_CalVmax_Handler,
		},
		{
			MethodName: "cal_shock_damage",
			Handler:    _ImpactEffectService_CalShockDamage_Handler,
		},
		{
			MethodName: "cal_dec_level",
			Handler:    _ImpactEffectService_CalDecLevel_Handler,
		},
		{
			MethodName: "cal_TsunamiArrivalTime",
			Handler:    _ImpactEffectService_Cal_TsunamiArrivalTime_Handler,
		},
		{
			MethodName: "cal_WaveAmplitudeUpperLimit",
			Handler:    _ImpactEffectService_Cal_WaveAmplitudeUpperLimit_Handler,
		},
		{
			MethodName: "cal_WaveAmplitudeLowerLimit",
			Handler:    _ImpactEffectService_Cal_WaveAmplitudeLowerLimit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "impactEffect.proto",
}
