// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: impactEffect.proto

package impactEffect

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Impactor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diameter int64 `protobuf:"varint,1,opt,name=diameter,proto3" json:"diameter,omitempty"`
	Density  int64 `protobuf:"varint,2,opt,name=density,proto3" json:"density,omitempty"`
	Velocity int64 `protobuf:"varint,3,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Theta    int64 `protobuf:"varint,4,opt,name=theta,proto3" json:"theta,omitempty"`
	Depth    int64 `protobuf:"varint,5,opt,name=depth,proto3" json:"depth,omitempty"`
	Ttype    int64 `protobuf:"varint,6,opt,name=ttype,proto3" json:"ttype,omitempty"`
}

func (x *Impactor) Reset() {
	*x = Impactor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_impactEffect_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Impactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Impactor) ProtoMessage() {}

func (x *Impactor) ProtoReflect() protoreflect.Message {
	mi := &file_impactEffect_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Impactor.ProtoReflect.Descriptor instead.
func (*Impactor) Descriptor() ([]byte, []int) {
	return file_impactEffect_proto_rawDescGZIP(), []int{0}
}

func (x *Impactor) GetDiameter() int64 {
	if x != nil {
		return x.Diameter
	}
	return 0
}

func (x *Impactor) GetDensity() int64 {
	if x != nil {
		return x.Density
	}
	return 0
}

func (x *Impactor) GetVelocity() int64 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

func (x *Impactor) GetTheta() int64 {
	if x != nil {
		return x.Theta
	}
	return 0
}

func (x *Impactor) GetDepth() int64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *Impactor) GetTtype() int64 {
	if x != nil {
		return x.Ttype
	}
	return 0
}

type KineticEnergy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KineticEnergy float32 `protobuf:"fixed32,1,opt,name=kinetic_energy,json=kineticEnergy,proto3" json:"kinetic_energy,omitempty"`
}

func (x *KineticEnergy) Reset() {
	*x = KineticEnergy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_impactEffect_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KineticEnergy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KineticEnergy) ProtoMessage() {}

func (x *KineticEnergy) ProtoReflect() protoreflect.Message {
	mi := &file_impactEffect_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KineticEnergy.ProtoReflect.Descriptor instead.
func (*KineticEnergy) Descriptor() ([]byte, []int) {
	return file_impactEffect_proto_rawDescGZIP(), []int{1}
}

func (x *KineticEnergy) GetKineticEnergy() float32 {
	if x != nil {
		return x.KineticEnergy
	}
	return 0
}

var File_impactEffect_proto protoreflect.FileDescriptor

var file_impactEffect_proto_rawDesc = []byte{
	0x0a, 0x12, 0x69, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x69, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x45, 0x66, 0x66, 0x65,
	0x63, 0x74, 0x22, 0x9e, 0x01, 0x0a, 0x08, 0x49, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x69, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x64, 0x69, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x64, 0x65,
	0x6e, 0x73, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x65, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x68, 0x65, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x36, 0x0a, 0x0d, 0x4b, 0x69, 0x6e, 0x65, 0x74, 0x69, 0x63, 0x45, 0x6e,
	0x65, 0x72, 0x67, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x6b, 0x69, 0x6e, 0x65, 0x74, 0x69, 0x63, 0x5f,
	0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x6b, 0x69,
	0x6e, 0x65, 0x74, 0x69, 0x63, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x32, 0x60, 0x0a, 0x13, 0x49,
	0x6d, 0x70, 0x61, 0x63, 0x74, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x49, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x65, 0x74, 0x69, 0x63,
	0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x12, 0x16, 0x2e, 0x69, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x45,
	0x66, 0x66, 0x65, 0x63, 0x74, 0x2e, 0x49, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x1a, 0x1b,
	0x2e, 0x69, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x2e, 0x4b, 0x69,
	0x6e, 0x65, 0x74, 0x69, 0x63, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x22, 0x00, 0x42, 0x32, 0x5a,
	0x30, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f,
	0x72, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x45, 0x66,
	0x66, 0x65, 0x63, 0x74, 0x2f, 0x69, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x45, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_impactEffect_proto_rawDescOnce sync.Once
	file_impactEffect_proto_rawDescData = file_impactEffect_proto_rawDesc
)

func file_impactEffect_proto_rawDescGZIP() []byte {
	file_impactEffect_proto_rawDescOnce.Do(func() {
		file_impactEffect_proto_rawDescData = protoimpl.X.CompressGZIP(file_impactEffect_proto_rawDescData)
	})
	return file_impactEffect_proto_rawDescData
}

var file_impactEffect_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_impactEffect_proto_goTypes = []interface{}{
	(*Impactor)(nil),      // 0: impactEffect.Impactor
	(*KineticEnergy)(nil), // 1: impactEffect.KineticEnergy
}
var file_impactEffect_proto_depIdxs = []int32{
	0, // 0: impactEffect.ImpactEffectService.GetKineticEnergy:input_type -> impactEffect.Impactor
	1, // 1: impactEffect.ImpactEffectService.GetKineticEnergy:output_type -> impactEffect.KineticEnergy
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_impactEffect_proto_init() }
func file_impactEffect_proto_init() {
	if File_impactEffect_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_impactEffect_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Impactor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_impactEffect_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KineticEnergy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_impactEffect_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_impactEffect_proto_goTypes,
		DependencyIndexes: file_impactEffect_proto_depIdxs,
		MessageInfos:      file_impactEffect_proto_msgTypes,
	}.Build()
	File_impactEffect_proto = out.File
	file_impactEffect_proto_rawDesc = nil
	file_impactEffect_proto_goTypes = nil
	file_impactEffect_proto_depIdxs = nil
}
